/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.rest.application.config;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author Franky Laseure
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(eve.restservices.RSCategory.class);
        resources.add(eve.restservices.RSConstellation.class);
        resources.add(eve.restservices.RSEvetype.class);
        resources.add(eve.restservices.RSGraphic.class);
        resources.add(eve.restservices.RSMarket_group.class);
        resources.add(eve.restservices.RSRace.class);
        resources.add(eve.restservices.RSRegion.class);
        resources.add(eve.restservices.RSStation.class);
        resources.add(eve.restservices.RSStation_service.class);
        resources.add(eve.restservices.RSSystem.class);
        resources.add(eve.restservices.RSTypegroup.class);
        return resources;
    }
}
//needs customization by programmer ?
